[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel"


[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter directory or open file"


[[mgr.prepend_keymap]]
on = "<Right>"
run = "plugin smart-enter"
desc = "Enter directory or open file"


[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane min-preview"
desc = "Toggle preview pane"


[[mgr.append_keymap]]
on = ["g", "p"]
run = "cd ~/Pictures"
desc = "Go ~/Pictures"


[[mgr.append_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to the root of Git repo"


[[mgr.append_keymap]]
on = ["g", "t"]
run = "cd ~/.local/share/Trash/files"
desc = "Go to Trash"


[[mgr.append_keymap]]
on = ["g", "m"]
run = "cd /mnt"
desc = "Go /mnt"


[[mgr.prepend_keymap]]
on = ["<C-h>"]
run = "hidden toggle"
desc = "Toggle hidden files"


[[mgr.prepend_keymap]]
on = ["<C-j>"]
run = "arrow 20%"
desc = "Dash down"


[[mgr.prepend_keymap]]
on = ["<C-k>"]
run = "arrow -20%"
desc = "Dash cursor up"
