[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"


[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"


[[mgr.prepend_keymap]]
on = "<Right>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"


[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"


[[mgr.append_keymap]]
on = ["g", "p"]
run = "cd ~/Pictures"
desc = "Go ~/Pictures"


[[mgr.append_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to the root of Git repo"


[[mgr.append_keymap]]
on = ["g", "t"]
run = "cd ~/.local/share/Trash/files"
desc = "Go to Trash"
