# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Find
find_keyword = { fg = "#FF5555", bold = true, italic = true, underline = true }
find_position = { fg = "#FF5555", bold = true, italic = true }

# Marker
marker_copied = { fg = "#007e99", bg = "#007e99" }
marker_cut = { fg = "#007e99", bg = "#007e99" }
marker_marked = { fg = "#FF5555", bg = "#FF5555" }
marker_selected = { fg = "#8be9fd", bg = "#8be9fd" }

# Count
count_copied = { fg = "#ffffff", bg = "#007e99" }
count_cut = { fg = "#ffffff", bg = "#007e99" }
count_selected = { fg = "#e6e1e5", bg = "#8be9fd" }

# Border
border_style  = { fg = "#bd93f9" }

# : ]]]


# : Status [[[

[status]
overall = { fg = "#bd93f9" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#bd93f9", bg = "#282A36" }
progress_error = { fg = "#FF5555", bg = "#282A36" }

# Permissions
perm_type = { fg = "#ff79c6" }
perm_write = { fg = "#8be9fd" }
perm_exec = { fg = "#FF5555" }
perm_read = { fg = "#007e99" }
perm_sep = { fg = "#3f0099" }

# : ]]]


# : Mode [[[

[mode]

normal_main = { bg = "#bd93f9", fg = "#e6e1e5", bold = true }
normal_alt  = { bg = "#333545", fg = "#ffffff" }

select_main = { bg = "#ff79c6", fg = "#e6e1e5", bold = true }
select_alt  = { bg = "#333545", fg = "#ffffff" }

unset_main = { bg = "#8be9fd", fg = "#000000", bold = true }
unset_alt  = { bg = "#333545", fg = "#ffffff" }

# : ]]]


# : Input [[[

[input]
border = { fg = "#bd93f9" }
title = {}
value = { fg = "#ffffff" }
selected = { reversed = true }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#bd93f9", bold = true, bg = "#282A36" }
inactive = { fg = "#ff79c6", bg = "#282A36" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#bd93f9", bg = "#e6e1e5" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#bd93f9" }
title = {}
hovered = { fg = "#007e99", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#282A36" }
cand = { fg = "#bd93f9" }
rest = { fg = "#e6e1e5" }
desc = { fg = "#ffffff" }
separator = " ▶ "
separator_style = { fg = "#ffffff" }

# : ]]]

# : Spotter [[[

[spot]
border   = { fg = "#bd93f9" }
title    = { fg = "#bd93f9" }
tbl_col  = { fg = "#ffffff" }
tbl_cell = { fg = "#ffffff", bg = "#282A36" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#e6e1e5", bg = "#ff79c6" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#8be9fd" }
title_warn = { fg = "#bd93f9" }
title_error = { fg = "#FF5555" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { mime = "*", is = "orphan", fg = "#ffffff", bg = "#990000" },
    { mime = "application/*exec*", fg = "#FF5555" },

    # Fallback
    { url = "*", fg = "#ffffff" },
    { url = "*/", fg = "#bd93f9" },
]

# : ]]]
